version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.Mongo
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./src/MongoServer/config/.env.local
    environment:
      - NODE_ENV=local
      - CONNECTION_STRING
      - PORT
      - RECOMMEND_PORT
      - RECOMMEND_HOST
    depends_on:
      - mongo
      - recommend
    container_name: MongoServer

  recommend:
    build:
      context: .
      dockerfile: dockerfile.Recommend
    ports:
      - "${RECOMMEND_PORT}:${RECOMMEND_PORT}"
    env_file:
      - ./src/MongoServer/config/.env.local
    environment:
      - RECOMMEND_PORT
      - RECOMMEND_HOST
    depends_on:
      - mongo
    container_name: RecommendServer

  mongo:
    image: mongo:latest
    container_name: MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./movies.json:/movies.json
      - ./categories.json:/categories.json
    command: ["mongod", "--logpath", "/data/db/mongo.log", "--logappend"]

volumes:
  mongo_data: