# Use Node.js for development
FROM node:latest

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port for the React server
EXPOSE 3000

# Start the React server
CMD ["npm", "start"]